### ISSUE TITLE
Log extraction is failing on files with a bad format at the first line

### ISSUE THREAD

**Issue by a-cordier** [ezpaarse-project/ezpaarse#39]
Hello,

Considering the following log file extract:
[bounday-issue-nok.txt](https://github.com/ezpaarse-project/ezpaarse/files/349665/bounday-issue-nok.txt)
*
Log extractor will fail as first line doesn't fit expected format (no event found)

Now let's move the first line at position 2
[bounday-issue-ok.txt](https://github.com/ezpaarse-project/ezpaarse/files/349671/bounday-issue-ok.txt)

Extraction works (116 events found)

This was encountered using predefined setting "France - Université Lille 2"

Best,

Antoine

**Comment by tporquet** [comment]
Since the 2.8 version of ezPAARSE, it is able to work on the first 10 lines to decide if the log format recognition is working or not (instead of only the first one).
The extract you provided us with is working on the national (and up to date) instance http://ezpaarse.couperin.org (v2.8.1)

What is the version of the ezPAARSE you are using ?

**Comment by a-cordier** [comment]
Good point,
The instance running was a 2.7 version.
Thank you
